GET http://localhost:4000/ping

###
GET http://localhost:4000/eventos

###
GET http://localhost:4000/eventos/evento-js-avancado

###

GET http://localhost:4000/eventos/6c648b98-a6ed-44a4-9741-4b286d9c8c8d

###
GET http://localhost:4000/eventos/validar/evento-js-avancado/9c02373a-ef1f-478f-b7f7-5cc88a4ce341

###
POST http://localhost:4000/eventos/acessar
Content-Type: application/json

{
    "id": "9c02373a-ef1f-478f-b7f7-5cc88a4ce341",
    "senha": "js2024"

}

###
POST http://localhost:4000/eventos/evento-dev-java/convidado
Content-Type: application/json

{
    "id": "a8f3f6a3-5e9b-4da9-83d2-01ebb6c7c9f4",
    "nome": "Viviane Aguiar",
    "email": "vivianeaguiar@outlook.com",
    "confirmado": true,
    "possuiAcompanhante": true,
    "qtdeAcompanhantes": 10
}

###
POST http://localhost:4000/eventos
Content-Type: application/json

{
    "id": "560f4977-dad5-4a19-bc7f-fc18a496bb8f",
    "alias": "evento-fullCicle-Dev",
    "nome": "Semana FullCycle.Dev",
    "data": "2024-12-31T23:59:59",
    "local": "Rio de Janeiro",
    "descricao": "Evento de tecnologia para Senior",
    "senha": "devsenior2025",
    "imagem": "https://fullcycle.com.br/wp-content/uploads/2024/08/linkedin-artes-11-1200x454-1.png",
    "imagemBackground": "https://fullcycle.com.br/wp-content/uploads/2024/08/linkedin-artes-11-1200x454-1.png",
    "publicoEsperado": 1000,
    "convidados": [{
        "id": "a8f3f6a3-5e9b-4da9-83d2-01ebb6c7c9f4",
        "nome": "Viviane Aguiar",
        "email": "vivianeaguiar@outlook.com",
        "confirmado": true,
        "possuiAcompanhante": true,
        "qtdeAcompanhantes": 10
    }]
}